version: "3"
services:
  app:
    build: .
    command: ./wait-for selenium:4444 -- npm test -- --host selenium
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome
    expose:
      - "4444"
